version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passlocker-dev
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate
    environment:
      POSTGRESQL_URL: 'postgres://postgres:postgres@db:1234/postgres?sslmode=disable'
      PORT: 8080
      JWT_KEY: VHTFsNM1Am
    networks:
      - app-network
  db:
    image: postgres:13.4
    container_name: passlocker-db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - "1234"
    command:
      -p 1234
    ports:
      - "1234:1234"

    networks:
      - app-network
  migrate:
    container_name: passlocker-migrate
    image: "migrate/migrate:v4.4.0"
    depends_on:
      - db
    volumes:
      - "./db/migrations:/migrations"
    command: [ "-path", "/migrations/", "-database", "postgres://postgres:postgres@db:1234/postgres?sslmode=disable", "up" ]
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
